plugins {
    id 'groovy'
    id 'application'
    id 'war'
}

group   = 'rb.aczg'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation localGroovy()
    implementation 'org.postgresql:postgresql:42.7.3'
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    testImplementation 'org.spockframework:spock-core:2.3-groovy-4.0'
    testImplementation 'org.junit.platform:junit-platform-launcher:1.10.2'
}

war {
    archiveFileName = 'linketinder.war'
}

test {
    useJUnitPlatform()

    testLogging {
        events 'passed', 'skipped', 'failed'
        showStandardStreams = false
        exceptionFormat = 'full'
    }
}